@PACKAGE_INIT@

set("@PROJECT_NAME@_WITH_QP" @WITH_QP@)
set("@PROJECT_NAME@_WITH_XDP" @WITH_XDP@)
set("@PROJECT_NAME@_WITH_BLAS" @WITH_BLAS@)

if(NOT TARGET "@PROJECT_NAME@::@PROJECT_NAME@")
  include("${CMAKE_CURRENT_LIST_DIR}/@PROJECT_NAME@-targets.cmake")

  if(NOT BLAS_FOUND AND @PROJECT_NAME@_WITH_BLAS)
    find_package("BLAS")
  endif()
endif()
